version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306" # ローカルのポート3306をドッカーの3306に接続する
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: